name: Release Multi-Platform

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # WICHTIG: Erlaubt das Erstellen von Releases

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Verhindert, dass alle anderen Jobs abbrechen, wenn einer mal hakt
      matrix:
        include:
          - goos: linux
            goarch: amd64
            file: athan-linux-amd64
          - goos: linux
            goarch: arm
            goarm: 7
            file: athan-raspberry-pi
          - goos: windows
            goarch: amd64
            file: athan-windows-amd64.exe
          - goos: darwin
            goarch: amd64
            file: athan-mac-intel
          - goos: darwin
            goarch: arm64
            file: athan-mac-m1-m2

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true # Beschleunigt den Build bei Wiederholung

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: go build -v -o ${{ matrix.file }}

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
